In [1]:
import TweetDataFrame as TDF
import Natural_Language_Processing as NLP
from sklearn.feature_extraction.text import CountVectorizer
import tweepy as tw
import pandas as pd
import numpy as np

In [2]:
dico = pd.read_excel('dictionary_sentiment.xlsx',sheet_name=1)

In [3]:
Data = TDF.search("Airbus", "2020-12-07", 10, "en")

Authentification ok


In [4]:
Data.columns

Index(['Text', 'User', 'Date', 'Search Word'], dtype='object')

In [5]:
tweet = Data['Text'][0]

In [6]:
f= open("dict_mot/stop_words_english.txt","r")
stop_words_en=f.read().splitlines()
f.close

<function TextIOWrapper.close()>

In [7]:
bag_of_words = pd.DataFrame()

In [8]:
for i in range(Data.shape[0]):
    tweet = Data.Text[i]
    words,BOW = NLP.bagofwords(tweet,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words = NLP.addinbow(bag_of_words,words,BOW)
bag_of_words

ahead  airbus  capetown  capetownint  endless  flight  happy  hello  lift  \
0    1.0       1       1.0          1.0      1.0     1.0    1.0    1.0   1.0   
0    0.0       1       0.0          0.0      0.0     0.0    0.0    0.0   0.0   
0    0.0       1       0.0          0.0      0.0     0.0    0.0    0.0   0.0   
0    0.0       1       0.0          0.0      0.0     0.0    0.0    0.0   0.0   
0    0.0       1       0.0          0.0      0.0     0.0    0.0    0.0   0.0   
0    0.0       1       0.0          0.0      0.0     3.0    0.0    0.0   0.0   
0    0.0       1       0.0          0.0      0.0     0.0    0.0    0.0   0.0   
0    0.0       1       0.0          0.0      0.0     0.0    0.0    0.0   0.0   
0    0.0       1       0.0          0.0      0.0     1.0    0.0    0.0   0.0   
0    0.0       1       0.0          0.0      0.0     0.0    0.0    0.0   0.0   

   liftairlinesa  ...  airbuspress  avgeek  avgeeks  aviation  aviationlovers  \
0            1.0  ...            0       0        0         0               0   
0            0.0  ...            0       0        0         0               0   
0            0.0  ...            0       0        0         0               0   
0            0.0  ...            0       0        0         0               0   
0            0.0  ...            0       0        0         0               0   
0            0.0  ...            0       0        0         0               0   
0            0.0  ...            0       0        0         0               0   
0            0.0  ...            0       0        0         0               0   
0            0.0  ...            0       0        0         0               0   
0            0.0  ...            1       1        1         1               1   

   cdg  deltaairlines  skyteam  taking  tdtdzemqcc  
0    0              0        0       0           0  
0    0              0        0       0           0  
0    0              0        0       0           0  
0    0              0        0       0           0  
0    0              0        0       0           0  
0    0              0        0       0           0  
0    0              0        0       0           0  
0    0              0        0       0           0  
0    0              0        0       0           0  
0    1              1        2       1           1  

[10 rows x 144 columns]

In [9]:
Data.Text[0]

'@NielSwart_ZA @capetownint @LiftAirlineSA @ortambo_int @Airbus @Wesgro @Airports_ZA @SATravelTrade @superbalist Hello Lift! May there be endless happy flights ahead. #CapeTown'

In [10]:
Data = TDF.search_author('CNNBusiness',20)

Authentification ok


In [11]:
Data

Text       Author  \
0   As the NBA's plans to create some kind of "bub...  CNNBusiness   
1   One $748 billion proposal includes money for s...  CNNBusiness   
2   Half of US households told Bankrate their inco...  CNNBusiness   
3   Reddit is speeding up its push into video http...  CNNBusiness   
4   With the pandemic as a backdrop, more than 14 ...  CNNBusiness   
5   Small space? Tight budget? Try these holiday d...  CNNBusiness   
6   Breaking into a brand new field may seem impos...  CNNBusiness   
7   Bob Dylan has agreed to sell his entire catalo...  CNNBusiness   
8   Silicon Valley has been the epicenter of the t...  CNNBusiness   
9   About 17% of America's restaurants have alread...  CNNBusiness   
10  Despite the reputational risk, Chinese compani...  CNNBusiness   
11  SpaceX's Falcon 9 rocket launched into space S...  CNNBusiness   
12  A Florida business owner who was once down on ...  CNNBusiness   
13  The US Commerce Department confirmed Sunday it...  CNNBusiness   
14  Disney is partnering with Kugali Media to crea...  CNNBusiness   
15  Hawaii is offering free round trip tickets to ...  CNNBusiness   
16  Starbucks is betting that by flooding the mark...  CNNBusiness   
17  Small space? Tight budget? Try these holiday d...  CNNBusiness   
18  Bob Dylan has agreed to sell his entire catalo...  CNNBusiness   
19  About 17% of America's restaurants have alread...  CNNBusiness   

                  Date  
0  2020-12-14 12:01:09  
1  2020-12-14 11:56:37  
2  2020-12-14 11:01:02  
3  2020-12-14 10:41:03  
4  2020-12-14 10:01:06  
5  2020-12-14 09:01:07  
6  2020-12-14 08:36:01  
7  2020-12-14 05:01:08  
8  2020-12-14 03:30:08  
9  2020-12-14 03:01:03  
10 2020-12-14 01:01:06  
11 2020-12-13 23:09:04  
12 2020-12-13 23:01:03  
13 2020-12-13 22:40:56  
14 2020-12-13 21:01:05  
15 2020-12-13 15:01:06  
16 2020-12-13 14:01:04  
17 2020-12-13 09:01:10  
18 2020-12-13 05:01:03  
19 2020-12-13 03:01:06

In [12]:
bag_of_words = pd.DataFrame()

In [13]:
for i in range(Data.shape[0]):
    tweet = Data.Text[i]
    words,BOW = NLP.bagofwords(tweet,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words = NLP.addinbow(bag_of_words,words,BOW)
bag_of_words

also  amid  bubble  confront  create  grappling  isolation  kind  national  \
0   1.0   1.0     1.0       1.0     1.0        1.0        1.0   1.0       1.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     1.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   
0   0.0   0.0     0.0       0.0     0.0        0.0        0.0   0.0       0.0   

   nba  ...  including  location  market  pickup  smaller  starbucks  steal  \
0  1.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        1.0       1.0     1.0     1.0      1.0        1.0    1.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   
0  0.0  ...        0.0       0.0     0.0     0.0      0.0        0.0    0.0   

   store  thru  type  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    1.0   1.0   1.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  
0    0.0   0.0   0.0  

[20 rows x 246 columns]

In [14]:
dataset = pd.read_csv('dataset_sentiment.csv',sep=',',encoding='latin-1',header=None,names=['sentiment','text'])

In [15]:
dataset

sentiment                                               text
0      neutral  According to Gran , the company has no plans t...
1      neutral  Technopolis plans to develop in stages an area...
2     negative  The international electronic industry company ...
3     positive  With the new production plant the company woul...
4     positive  According to the company 's updated strategy f...
...        ...                                                ...
4841  negative  LONDON MarketWatch -- Share prices ended lower...
4842   neutral  Rinkuskiai 's beer sales fell by 6.5 per cent ...
4843  negative  Operating profit fell to EUR 35.4 mn from EUR ...
4844  negative  Net sales of the Paper segment decreased to EU...
4845  negative  Sales in Finland decreased by 10.5 % in Januar...

[4846 rows x 2 columns]

In [16]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()

In [17]:
X = dataset[['text']]
y = dataset[['sentiment']]

In [18]:
y = enc.fit_transform(y)

In [19]:
y = y-1 # neutral = 0, positive = 1, negative = -1

In [20]:
X_train,y_train = X[:int(0.2*len(X))],y[:int(0.2*len(X))] #la création du bag_of_words prend énormement de temps d'ou le 0.2 ici

In [21]:
X_train = list(X_train['text'])

In [23]:
bag_of_words = pd.DataFrame()
for i in range(len(X_train)):
    text = X_train[i]
    words,BOW = NLP.bagofwords(text,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words = NLP.addinbow(bag_of_words,words,BOW)
bag_of_words

according  although  company  gran  growing  move  plan  production  \
0         1.0       1.0      2.0   1.0      1.0   1.0   1.0         1.0   
0         0.0       0.0      1.0   0.0      0.0   0.0   1.0         0.0   
0         0.0       0.0      2.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      1.0   0.0      0.0   0.0   0.0         2.0   
0         1.0       0.0      1.0   0.0      0.0   0.0   0.0         0.0   
..        ...       ...      ...   ...      ...   ...   ...         ...   
0         0.0       0.0      1.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   

    russia  area  ...  confidence  expressed  rantanen  productional  \
0      1.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   1.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
..     ...   ...  ...         ...        ...       ...           ...   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           1.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   

    kemijoki  river  spanning  beating  inclusive  vat  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
..       ...    ...       ...      ...        ...  ...  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        1.0    1.0       1.0      0.0          0    0  
0        0.0    0.0       0.0      1.0          0    0  
0        0.0    0.0       0.0      0.0          1    1  

[969 rows x 2832 columns]

In [24]:
y_train.shape

(969, 1)

In [34]:
y_train = y_train.reshape(-1)
y_train.shape

(969,)

In [35]:
bag_of_words.shape

(969, 2832)

In [62]:
bag_of_words_train = bag_of_words.copy()

In [63]:
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import OneClassSVM
from sklearn.model_selection import cross_val_score

In [70]:
gaussian_sentiment = GaussianNB()
scores_gaussian = cross_val_score(gaussian_sentiment,bag_of_words_train,y_train,cv=5)

In [99]:
scores_gaussian # moyenne 0.726

array([0.7371134 , 0.69587629, 0.70618557, 0.7371134 , 0.75647668])

In [77]:
svm_sentiment = OneClassSVM(kernel = 'rbf')

In [80]:
scores_SVM = cross_val_score(svm_sentiment,bag_of_words_train,y_train,cv=5,scoring='accuracy')

In [81]:
scores_SVM

array([0.34536082, 0.65463918, 0.17010309, 0.40206186, 0.43005181])

In [82]:
from sklearn.model_selection import GridSearchCV

In [94]:
param_grid = {'gamma':[0.1,0.01,0.5],'nu':[0.2,0.1,0.01]}

In [95]:
svm_sentiment = OneClassSVM(kernel = 'rbf')

In [96]:
grid_search = GridSearchCV(svm_sentiment,param_grid,cv=5,scoring='accuracy',return_train_score=True)
grid_search.fit(bag_of_words_train,y_train)

GridSearchCV(cv=5, estimator=OneClassSVM(),
             param_grid={'gamma': [0.1, 0.01, 0.5], 'nu': [0.2, 0.1, 0.01]},
             return_train_score=True, scoring='accuracy')

In [97]:
grid_search.best_score_

0.7545643929277283

In [98]:
grid_search.best_estimator_

OneClassSVM(gamma=0.01, nu=0.01)

In [101]:
nbneu = 0
nbpos = 0
nbneg = 0
for i in y_train:
    if i == 0:
        nbneu+=1
    if i == 1:
        nbpos+=1
    if i == -1:
        nbneg+=1
print('neutral: ',nbneu,' positiv: ',nbpos,' negative: ',nbneu)
        

neutral:  174  positiv:  757  negative:  174


In [105]:
bag_of_words_train

according  although  company  gran  growing  move  plan  production  \
0         1.0       1.0      2.0   1.0      1.0   1.0   1.0         1.0   
0         0.0       0.0      1.0   0.0      0.0   0.0   1.0         0.0   
0         0.0       0.0      2.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      1.0   0.0      0.0   0.0   0.0         2.0   
0         1.0       0.0      1.0   0.0      0.0   0.0   0.0         0.0   
..        ...       ...      ...   ...      ...   ...   ...         ...   
0         0.0       0.0      1.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   

    russia  area  ...  confidence  expressed  rantanen  productional  \
0      1.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   1.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
..     ...   ...  ...         ...        ...       ...           ...   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           1.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   

    kemijoki  river  spanning  beating  inclusive  vat  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
..       ...    ...       ...      ...        ...  ...  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        1.0    1.0       1.0      0.0          0    0  
0        0.0    0.0       0.0      1.0          0    0  
0        0.0    0.0       0.0      0.0          1    1  

[969 rows x 2832 columns]

In [107]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
kf = KFold(n_splits=5,shuffle=True)
for train_index,test_index in kf.split(y_train):
    X_train_fold, X_test_fold = bag_of_words_train.iloc[train_index], bag_of_words_train.iloc[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
    gaussian_sentiment = GaussianNB()
    gaussian_sentiment.fit(X_train_fold,y_train_fold)
    y_predict = gaussian_sentiment.predict(X_test_fold)
    print(confusion_matrix(y_test_fold,y_predict,labels=[-1, 0, 1]))

[[  3   1   6]
 [  0  16  22]
 [ 11  16 119]]
[[  2   2   3]
 [  0  14  18]
 [ 10  16 129]]
[[  1   0   7]
 [  1  12  28]
 [  9   9 127]]
[[  4   0   1]
 [  1  14  17]
 [ 13   8 136]]
[[  2   2   4]
 [  0   8  23]
 [ 10  11 133]]


Même si le GaussianNB a l'air de bien marcher on voit clairement que la sur représentation de '1' pose probème. Nous allons essayer de rééquilibrer un peu ca. Il existe plusieurs methodes, class_weight,sample_weight ou encore directement agir sur le dataframe d'entrainement

In [136]:
X_train =[]
y_train =[]
k=0
i=0
while k<500:
    if y[i]==-1:
        X_train.append(X['text'][i])
        y_train.append(y[i])
        k+=1
    i+=1
k=0
i=0
while k<500:
    if y[i]==0:
        X_train.append(X['text'][i])
        y_train.append(y[i])
        k+=1
    i+=1
k=0
i=0
while k<500:
    if y[i]==1:
        X_train.append(X['text'][i])
        y_train.append(y[i])
        k+=1
    i+=1

In [137]:
import random

c = list(zip(X_train, y_train))

random.shuffle(c)

X_train, y_train = zip(*c)

X_train = list(X_train)
y_train = list(y_train)

y_train=list(np.array(y_train).reshape(-1))

In [138]:
bag_of_words_train = pd.DataFrame()
for i in range(len(X_train)):
    text = X_train[i]
    words,BOW = NLP.bagofwords(text,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words_train = NLP.addinbow(bag_of_words_train,words,BOW)
bag_of_words_train

asx  august  based  contract  gold  guinea  lgl  lihir  ltd  new  ...  \
0   1.0     1.0    1.0       1.0   1.0     1.0  1.0    1.0  1.0  1.0  ...   
0   0.0     0.0    0.0       0.0   0.0     0.0  0.0    0.0  0.0  0.0  ...   
0   0.0     0.0    0.0       0.0   0.0     0.0  0.0    0.0  0.0  0.0  ...   
0   0.0     0.0    0.0       0.0   0.0     0.0  0.0    0.0  0.0  0.0  ...   
0   0.0     0.0    0.0       0.0   0.0     0.0  0.0    0.0  0.0  0.0  ...   
..  ...     ...    ...       ...   ...     ...  ...    ...  ...  ...  ...   
0   0.0     0.0    0.0       1.0   0.0     0.0  0.0    0.0  0.0  0.0  ...   
0   0.0     0.0    0.0       0.0   0.0     0.0  0.0    0.0  0.0  1.0  ...   
0   0.0     0.0    0.0       0.0   0.0     0.0  0.0    0.0  0.0  1.0  ...   
0   0.0     0.0    0.0       0.0   0.0     0.0  0.0    0.0  0.0  0.0  ...   
0   0.0     0.0    0.0       0.0   0.0     0.0  0.0    0.0  0.0  0.0  ...   

    launched  mastercard  regionally  unique  shipbuilding  training  ingen  \
0        0.0         0.0         0.0     0.0           0.0       0.0    0.0   
0        0.0         0.0         0.0     0.0           0.0       0.0    0.0   
0        0.0         0.0         0.0     0.0           0.0       0.0    0.0   
0        0.0         0.0         0.0     0.0           0.0       0.0    0.0   
0        0.0         0.0         0.0     0.0           0.0       0.0    0.0   
..       ...         ...         ...     ...           ...       ...    ...   
0        0.0         0.0         0.0     0.0           0.0       1.0    0.0   
0        0.0         0.0         0.0     0.0           0.0       0.0    1.0   
0        0.0         0.0         0.0     0.0           0.0       0.0    0.0   
0        0.0         0.0         0.0     0.0           0.0       0.0    0.0   
0        0.0         0.0         0.0     0.0           0.0       0.0    0.0   

    respiratory  buying  venture  
0           0.0     0.0      0.0  
0           0.0     0.0      0.0  
0           0.0     0.0      0.0  
0           0.0     0.0      0.0  
0           0.0     0.0      0.0  
..          ...     ...      ...  
0           0.0     0.0      0.0  
0           1.0     0.0      0.0  
0           0.0     1.0      1.0  
0           0.0     0.0      0.0  
0           0.0     0.0      0.0  

[1500 rows x 3818 columns]

In [139]:
gaussian_sentiment = GaussianNB()
scores_gaussian = cross_val_score(gaussian_sentiment,bag_of_words_train,y_train,cv=5)
scores_gaussian 

array([0.63333333, 0.64      , 0.68      , 0.65666667, 0.62333333])

In [140]:
svm_sentiment = OneClassSVM(kernel = 'rbf',gamma=0.01,nu=0.01)
scores_gaussian = cross_val_score(svm_sentiment,bag_of_words_train,y_train,cv=5,scoring='accuracy')
scores_gaussian 

array([0.38333333, 0.29333333, 0.28666667, 0.35333333, 0.32333333])