In [1]:
import TweetDataFrame as TDF
import Natural_Language_Processing as NLP
from sklearn.feature_extraction.text import CountVectorizer
import tweepy as tw
import pandas as pd
import numpy as np

In [31]:
dico = pd.read_excel('dictionary_sentiment.xlsx',sheet_name=1)

In [32]:
Data = TDF.search("Airbus", "2020-12-07", 10, "en")

Authentification ok


In [33]:
Data.columns

Index(['Text', 'User', 'Date', 'Search Word'], dtype='object')

In [34]:
tweet = Data['Text'][0]

In [35]:
f= open("dict_mot/stop_words_english.txt","r")
stop_words_en=f.read().splitlines()
f.close

<function TextIOWrapper.close()>

In [36]:
bag_of_words = pd.DataFrame()

In [37]:
for i in range(Data.shape[0]):
    tweet = Data.Text[i]
    words,BOW = NLP.bagofwords(tweet,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words = NLP.addinbow(bag_of_words,words,BOW)
bag_of_words

airbus  aircraft  anti  aviation  besides  boeing  breakthrough  china  \
0       1       1.0   1.0       1.0      1.0     1.0           1.0    1.0   
0       1       0.0   0.0       0.0      0.0     0.0           0.0    0.0   
0       1       0.0   0.0       0.0      0.0     0.0           0.0    0.0   
0       1       0.0   0.0       0.0      0.0     0.0           0.0    0.0   
0       1       0.0   0.0       0.0      0.0     0.0           0.0    0.0   
0       1       0.0   0.0       0.0      0.0     0.0           0.0    0.0   
0       1       0.0   0.0       0.0      0.0     0.0           0.0    0.0   
0       1       0.0   0.0       0.0      0.0     0.0           0.0    0.0   
0       1       0.0   0.0       0.0      0.0     0.0           0.0    0.0   
0       1       0.0   0.0       0.0      0.0     0.0           0.0    0.0   

   chinese  choice  ...  gone  greenwich  hear  past  see  azman  flight  \
0      2.0     1.0  ...   0.0        0.0   0.0   0.0  0.0      0       0   
0      0.0     0.0  ...   0.0        0.0   0.0   0.0  0.0      0       0   
0      0.0     0.0  ...   0.0        0.0   0.0   0.0  0.0      0       0   
0      0.0     0.0  ...   0.0        0.0   0.0   0.0  0.0      0       0   
0      0.0     0.0  ...   0.0        0.0   0.0   0.0  0.0      0       0   
0      0.0     0.0  ...   0.0        0.0   0.0   0.0  0.0      0       0   
0      0.0     0.0  ...   0.0        0.0   0.0   0.0  0.0      0       0   
0      0.0     0.0  ...   0.0        0.0   0.0   0.0  0.0      0       0   
0      0.0     0.0  ...   1.0        1.0   1.0   1.0  1.0      0       0   
0      0.0     0.0  ...   0.0        0.0   0.0   0.0  0.0      1       1   

   launch  second  seek  
0       0       0     0  
0       0       0     0  
0       0       0     0  
0       0       0     0  
0       0       0     0  
0       0       0     0  
0       0       0     0  
0       0       0     0  
0       0       0     0  
0       1       1     1  

[10 rows x 104 columns]

In [38]:
Data.Text[0]

'C919 Chinese civil aviation passenger aircraft manufacturing project. A breakthrough from zero to one. It seems so meaningless in the eyes of anti-Chinese scholars. After success, it will provide people all over the world with a third choice besides Airbus and Boeing   #china https://t.co/NarVjMfR7A'

In [39]:
Data = TDF.search_author('CNNBusiness',20)

Authentification ok


In [40]:
Data

Text       Author  \
0   More than 170 prominent business leaders have ...  CNNBusiness   
1   A second round of stimulus payments are on the...  CNNBusiness   
2   Fiat Chrysler Automobiles and Groupe PSA, the ...  CNNBusiness   
3   The results of Georgia's Senate runoffs will p...  CNNBusiness   
4   Microsoft knows there's an Xbox shortage. It's...  CNNBusiness   
5   Haven, the health care company founded in 2018...  CNNBusiness   
6   Chipotle is adding cauliflower rice to its men...  CNNBusiness   
7   Janet Yellen, President-elect Joe Biden's pick...  CNNBusiness   
8   McDonald's is launching new sandwiches next mo...  CNNBusiness   
9   The Dow tumbled more than 600 points around mi...  CNNBusiness   
10  Investors are gearing up for a turbocharged 20...  CNNBusiness   
11  Google workers have formed the company's first...  CNNBusiness   
12  Work-related deaths reached a 12-year high in ...  CNNBusiness   
13  A digitally created fake Queen Elizabeth II da...  CNNBusiness   
14  These robots can boogie down better than most ...  CNNBusiness   
15  Prince Harry and Meghan, Duchess of Sussex, ha...  CNNBusiness   
16  2020 was tough on many industries, but the aut...  CNNBusiness   
17  This California teen started a nonprofit to he...  CNNBusiness   
18  This Egyptian spa is offering snake massages h...  CNNBusiness   
19  Beyoncé will offer $5,000 grants to help 100 p...  CNNBusiness   

                  Date  
0  2021-01-05 00:34:03  
1  2021-01-04 23:32:03  
2  2021-01-04 22:33:02  
3  2021-01-04 22:16:03  
4  2021-01-04 21:41:47  
5  2021-01-04 20:29:07  
6  2021-01-04 20:00:09  
7  2021-01-04 19:30:06  
8  2021-01-04 19:00:06  
9  2021-01-04 17:18:41  
10 2021-01-04 17:08:22  
11 2021-01-04 16:01:07  
12 2021-01-04 13:01:08  
13 2021-01-04 11:01:05  
14 2021-01-04 09:01:13  
15 2021-01-04 08:01:02  
16 2021-01-04 05:01:03  
17 2021-01-04 02:01:05  
18 2021-01-04 00:01:07  
19 2021-01-03 23:01:02

In [41]:
bag_of_words = pd.DataFrame()

In [42]:
for i in range(Data.shape[0]):
    tweet = Data.Text[i]
    words,BOW = NLP.bagofwords(tweet,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words = NLP.addinbow(bag_of_words,words,BOW)
bag_of_words

accept  biden  business  college  congress  declared  electoral  joe  \
0     1.0    1.0       1.0      1.0       1.0       1.0        1.0  1.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    1.0       0.0      0.0       0.0       0.0        0.0  1.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   
0     0.0    0.0       0.0      0.0       0.0       0.0        0.0  0.0   

   leader  letter  ...  crisis  due  eviction  facing  foreclosure  grant  \
0     1.0     1.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       0    0         0       0            0      0   
0     0.0     0.0  ...       1    1         1       1            1      1   

   housing  ivkquigbme  offer  people  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        0           0      0       0  
0        

In [43]:
dataset = pd.read_csv('dataset_sentiment.csv',sep=',',encoding='latin-1',header=None,names=['sentiment','text'])

In [44]:
dataset

sentiment                                               text
0      neutral  According to Gran , the company has no plans t...
1      neutral  Technopolis plans to develop in stages an area...
2     negative  The international electronic industry company ...
3     positive  With the new production plant the company woul...
4     positive  According to the company 's updated strategy f...
...        ...                                                ...
4841  negative  LONDON MarketWatch -- Share prices ended lower...
4842   neutral  Rinkuskiai 's beer sales fell by 6.5 per cent ...
4843  negative  Operating profit fell to EUR 35.4 mn from EUR ...
4844  negative  Net sales of the Paper segment decreased to EU...
4845  negative  Sales in Finland decreased by 10.5 % in Januar...

[4846 rows x 2 columns]

In [45]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()

In [50]:
X = dataset[['text']]
y = dataset[['sentiment']]

In [51]:
y = enc.fit_transform(y)

In [52]:
y = y-1 # neutral = 0, positive = 1, negative = -1

In [20]:
# X_train,y_train = X[:int(0.2*len(X))],y[:int(0.2*len(X))] #la création du bag_of_words prend énormement de temps d'ou le 0.2 ici

In [21]:
# X_train = list(X_train['text'])

In [23]:
# bag_of_words = pd.DataFrame()
# for i in range(len(X_train)):
#     text = X_train[i]
#     words,BOW = NLP.bagofwords(text,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
#     bag_of_words = NLP.addinbow(bag_of_words,words,BOW)
# bag_of_words

according  although  company  gran  growing  move  plan  production  \
0         1.0       1.0      2.0   1.0      1.0   1.0   1.0         1.0   
0         0.0       0.0      1.0   0.0      0.0   0.0   1.0         0.0   
0         0.0       0.0      2.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      1.0   0.0      0.0   0.0   0.0         2.0   
0         1.0       0.0      1.0   0.0      0.0   0.0   0.0         0.0   
..        ...       ...      ...   ...      ...   ...   ...         ...   
0         0.0       0.0      1.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   

    russia  area  ...  confidence  expressed  rantanen  productional  \
0      1.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   1.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
..     ...   ...  ...         ...        ...       ...           ...   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           1.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   

    kemijoki  river  spanning  beating  inclusive  vat  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
..       ...    ...       ...      ...        ...  ...  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        1.0    1.0       1.0      0.0          0    0  
0        0.0    0.0       0.0      1.0          0    0  
0        0.0    0.0       0.0      0.0          1    1  

[969 rows x 2832 columns]

In [24]:
# y_train.shape

(969, 1)

In [34]:
# y_train = y_train.reshape(-1)
# y_train.shape

(969,)

In [35]:
# bag_of_words.shape

(969, 2832)

In [62]:
# bag_of_words_train = bag_of_words.copy()

In [23]:
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import OneClassSVM
from sklearn.model_selection import cross_val_score

In [70]:
# gaussian_sentiment = GaussianNB()
# scores_gaussian = cross_val_score(gaussian_sentiment,bag_of_words_train,y_train,cv=5)

In [99]:
# scores_gaussian # moyenne 0.726

array([0.7371134 , 0.69587629, 0.70618557, 0.7371134 , 0.75647668])

In [77]:
# svm_sentiment = OneClassSVM(kernel = 'rbf')

In [80]:
# scores_SVM = cross_val_score(svm_sentiment,bag_of_words_train,y_train,cv=5,scoring='accuracy')

In [81]:
# scores_SVM

array([0.34536082, 0.65463918, 0.17010309, 0.40206186, 0.43005181])

In [24]:
from sklearn.model_selection import GridSearchCV

In [94]:
# param_grid = {'gamma':[0.1,0.01,0.5],'nu':[0.2,0.1,0.01]}

In [95]:
# svm_sentiment = OneClassSVM(kernel = 'rbf')

In [96]:
# grid_search = GridSearchCV(svm_sentiment,param_grid,cv=5,scoring='accuracy',return_train_score=True)
# grid_search.fit(bag_of_words_train,y_train)

GridSearchCV(cv=5, estimator=OneClassSVM(),
             param_grid={'gamma': [0.1, 0.01, 0.5], 'nu': [0.2, 0.1, 0.01]},
             return_train_score=True, scoring='accuracy')

In [97]:
# grid_search.best_score_

0.7545643929277283

In [98]:
# grid_search.best_estimator_

OneClassSVM(gamma=0.01, nu=0.01)

In [101]:
# nbneu = 0
# nbpos = 0
# nbneg = 0
# for i in y_train:
#     if i == 0:
#         nbneu+=1
#     if i == 1:
#         nbpos+=1
#     if i == -1:
#         nbneg+=1
# print('neutral: ',nbneu,' positiv: ',nbpos,' negative: ',nbneu)
        

neutral:  174  positiv:  757  negative:  174


In [105]:
# bag_of_words_train

according  although  company  gran  growing  move  plan  production  \
0         1.0       1.0      2.0   1.0      1.0   1.0   1.0         1.0   
0         0.0       0.0      1.0   0.0      0.0   0.0   1.0         0.0   
0         0.0       0.0      2.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      1.0   0.0      0.0   0.0   0.0         2.0   
0         1.0       0.0      1.0   0.0      0.0   0.0   0.0         0.0   
..        ...       ...      ...   ...      ...   ...   ...         ...   
0         0.0       0.0      1.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   
0         0.0       0.0      0.0   0.0      0.0   0.0   0.0         0.0   

    russia  area  ...  confidence  expressed  rantanen  productional  \
0      1.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   1.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
..     ...   ...  ...         ...        ...       ...           ...   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           1.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   
0      0.0   0.0  ...         0.0        0.0       0.0           0.0   

    kemijoki  river  spanning  beating  inclusive  vat  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
..       ...    ...       ...      ...        ...  ...  
0        0.0    0.0       0.0      0.0          0    0  
0        0.0    0.0       0.0      0.0          0    0  
0        1.0    1.0       1.0      0.0          0    0  
0        0.0    0.0       0.0      1.0          0    0  
0        0.0    0.0       0.0      0.0          1    1  

[969 rows x 2832 columns]

In [107]:
# from sklearn.model_selection import KFold
# from sklearn.metrics import confusion_matrix
# kf = KFold(n_splits=5,shuffle=True)
# for train_index,test_index in kf.split(y_train):
#     X_train_fold, X_test_fold = bag_of_words_train.iloc[train_index], bag_of_words_train.iloc[test_index]
#     y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
#     gaussian_sentiment = GaussianNB()
#     gaussian_sentiment.fit(X_train_fold,y_train_fold)
#     y_predict = gaussian_sentiment.predict(X_test_fold)
#     print(confusion_matrix(y_test_fold,y_predict,labels=[-1, 0, 1]))

[[  3   1   6]
 [  0  16  22]
 [ 11  16 119]]
[[  2   2   3]
 [  0  14  18]
 [ 10  16 129]]
[[  1   0   7]
 [  1  12  28]
 [  9   9 127]]
[[  4   0   1]
 [  1  14  17]
 [ 13   8 136]]
[[  2   2   4]
 [  0   8  23]
 [ 10  11 133]]


Même si le GaussianNB a l'air de bien marcher on voit clairement que la sur représentation de '1' pose probème. Nous allons essayer de rééquilibrer un peu ca. Il existe plusieurs methodes, class_weight,sample_weight ou encore directement agir sur le dataframe d'entrainement

In [53]:
unique, counts = np.unique(y, return_counts=True)
print(unique,counts)

[-1.  0.  1.] [ 604 2879 1363]


In [54]:
X_train =[]
y_train =[]
k=0
i=0
while k<600:
    if y[i]==-1:
        X_train.append(X['text'][i])
        y_train.append(y[i])
        k+=1
    i+=1
k=0
i=0
while k<600:
    if y[i]==0:
        X_train.append(X['text'][i])
        y_train.append(y[i])
        k+=1
    i+=1
k=0
i=0
while k<600:
    if y[i]==1:
        X_train.append(X['text'][i])
        y_train.append(y[i])
        k+=1
    i+=1

In [55]:
import random

c = list(zip(X_train, y_train))

random.shuffle(c)

X_train, y_train = zip(*c)

X_train = list(X_train)
y_train = list(y_train)

y_train=list(np.array(y_train).reshape(-1))

In [56]:
bag_of_words_train = pd.DataFrame()
for i in range(len(X_train)):
    text = X_train[i]
    words,BOW = NLP.bagofwords(text,'en', stop_words=stop_words_en, remove_non_words=False, stemming=False)
    bag_of_words_train = NLP.addinbow(bag_of_words_train,words,BOW)
bag_of_words_train

bed  every   go  night  said  worrying  cameco  circuit  construction  \
0   1.0    1.0  1.0    1.0   1.0       1.0     0.0      0.0           0.0   
0   0.0    0.0  0.0    0.0   0.0       0.0     1.0      1.0           1.0   
0   0.0    0.0  0.0    0.0   0.0       0.0     0.0      0.0           0.0   
0   0.0    0.0  0.0    0.0   0.0       0.0     0.0      0.0           0.0   
0   0.0    0.0  0.0    0.0   0.0       0.0     0.0      0.0           0.0   
..  ...    ...  ...    ...   ...       ...     ...      ...           ...   
0   0.0    0.0  0.0    0.0   1.0       0.0     0.0      0.0           0.0   
0   0.0    0.0  0.0    0.0   0.0       0.0     0.0      0.0           0.0   
0   0.0    0.0  0.0    0.0   0.0       0.0     0.0      0.0           0.0   
0   0.0    0.0  0.0    0.0   0.0       0.0     0.0      0.0           0.0   
0   0.0    0.0  0.0    0.0   0.0       0.0     0.0      0.0           0.0   

    extraction  ...  chamber  pressurized  avenue  kidnapping  male  maple  \
0          0.0  ...      0.0          0.0     0.0         0.0   0.0    0.0   
0          1.0  ...      0.0          0.0     0.0         0.0   0.0    0.0   
0          0.0  ...      0.0          0.0     0.0         0.0   0.0    0.0   
0          0.0  ...      0.0          0.0     0.0         0.0   0.0    0.0   
0          0.0  ...      0.0          0.0     0.0         0.0   0.0    0.0   
..         ...  ...      ...          ...     ...         ...   ...    ...   
0          0.0  ...      0.0          0.0     0.0         0.0   0.0    0.0   
0          0.0  ...      0.0          0.0     1.0         1.0   1.0    1.0   
0          0.0  ...      0.0          0.0     0.0         0.0   0.0    0.0   
0          0.0  ...      0.0          0.0     0.0         0.0   0.0    0.0   
0          0.0  ...      0.0          0.0     0.0         0.0   0.0    0.0   

    shooting  terrorized  improving  motorcyclist  
0        0.0         0.0          0             0  
0        0.0         0.0          0             0  
0        0.0         0.0          0             0  
0        0.0         0.0          0             0  
0        0.0         0.0          0             0  
..       ...         ...        ...           ...  
0        0.0         0.0          0             0  
0        1.0         1.0          0             0  
0        0.0         0.0          0             0  
0        0.0         0.0          0             0  
0        0.0         0.0          1             2  

[1800 rows x 4261 columns]

In [57]:
gaussian_sentiment = GaussianNB()
scores_gaussian = cross_val_score(gaussian_sentiment,bag_of_words_train,y_train,cv=5)
scores_gaussian 

array([0.60277778, 0.65      , 0.58611111, 0.58333333, 0.58333333])

In [58]:
svm_sentiment = OneClassSVM(kernel = 'rbf',gamma=0.01,nu=0.01)
scores_gaussian = cross_val_score(svm_sentiment,bag_of_words_train,y_train,cv=5,scoring='accuracy')
scores_gaussian 

array([0.36111111, 0.325     , 0.31388889, 0.35      , 0.29722222])

In [59]:
from sklearn.ensemble import RandomForestClassifier 
rnd_sentiment = RandomForestClassifier(n_estimators=500,criterion='entropy')
scores_gaussian = cross_val_score(rnd_sentiment,bag_of_words_train,y_train,cv=5,scoring='accuracy')
scores_gaussian 

array([0.73888889, 0.725     , 0.75277778, 0.77222222, 0.79166667])

In [65]:
y_train = np.array(y_train)

In [67]:
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
kf = KFold(n_splits=5,shuffle=True)
for train_index,test_index in kf.split(y_train):
    X_train_fold, X_test_fold = bag_of_words_train.iloc[train_index], bag_of_words_train.iloc[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
    rnd_sentiment = RandomForestClassifier(n_estimators=500,criterion='entropy')
    rnd_sentiment.fit(X_train_fold,y_train_fold)
    y_predict = rnd_sentiment.predict(X_test_fold)
    print(confusion_matrix(y_test_fold,y_predict,labels=[-1, 0, 1]))

[[ 76  24  13]
 [  7 114  14]
 [  4  32  76]]
[[89 30 13]
 [ 4 87 13]
 [11 22 91]]
[[ 86  28  10]
 [  4 110   6]
 [  3  27  86]]
[[ 86  27  12]
 [  7 113  10]
 [  3  24  78]]
[[80 23  3]
 [ 4 97 10]
 [10 39 94]]
